<?php
/**
 * Implements hook_permission
 */

function my_block_permission() {
	return array(
		'administer my module' => array(
			'title' => t('Administer my module'),
			'description' => t('Perform administration tasks for my module.'),
		),
	);
}

/**
 * Implements hook_block_info()
 */

function my_block_block_info() {
	$blocks = array();
	$blocks['my_first_block'] = array(
		'info' => t('My custom block'),
		'access callback' => 'user_access',
		'access arguments' => array('administer my module')
	);

	return $blocks;
}

/**
 * Implements hook_block_view
 */

function my_block_block_view($delta = '') {
	$block = array();
	if ($delta == 'my_first_block') {
		if(user_access(1)){
			$block['subject'] = t('Block Subject');
			$block['content'] = t('Block Content');
		}
		else {
			$block['subject'] = t('Block Subject');
			$block['content'] = t('Access to view this content is denied.');
		}
	}

	return $block;
}
?>
